"""
Groundedness verification service.

After answer generation, verifies each factual claim against the
retrieved context using a small LLM call.

Single call to gpt-4o-mini (or Claude Haiku, or Gemini Flash).
Cost: ~$0.0005 per query.
"""

import json
import logging
from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any

from openai import OpenAI

try:
    from ..core.config import GroundednessConfig, LLMProvider
    from .models import Citation, RetrievalResult
except ImportError:
    from src.core.config import GroundednessConfig, LLMProvider
    from models import Citation, RetrievalResult

logger = logging.getLogger(__name__)


@dataclass
class ClaimVerification:
    """One verified claim from the answer."""

    claim_text: str  # The sentence/fragment being verified
    cited_source: Optional[str]  # e.g., "Executive Summary, p.11" or None if uncited
    grounded: bool  # True if supported by cited source
    confidence: float  # 0.0 - 1.0
    reason: str  # Short LLM-generated reason


@dataclass
class GroundednessReport:
    """Output of groundedness verification."""

    verified: bool  # Overall pass: >= threshold of claims grounded
    overall_score: float  # Fraction of claims grounded (0-1)
    num_claims: int
    num_grounded: int
    num_ungrounded: int
    claims: List[ClaimVerification] = field(default_factory=list)
    provider_used: str = ""  # "openai" / "claude" / "gemini"
    error: Optional[str] = None  # If verification itself failed

    def to_dict(self) -> Dict[str, Any]:
        return {
            "verified": self.verified,
            "overall_score": round(self.overall_score, 3),
            "num_claims": self.num_claims,
            "num_grounded": self.num_grounded,
            "num_ungrounded": self.num_ungrounded,
            "claims": [
                {
                    "claim_text": c.claim_text,
                    "cited_source": c.cited_source,
                    "grounded": c.grounded,
                    "confidence": round(c.confidence, 3),
                    "reason": c.reason,
                }
                for c in self.claims
            ],
            "error": self.error,
        }


GROUNDEDNESS_SYSTEM_PROMPT = """You verify whether factual claims in an answer are supported by the cited source passages.

You will be given:
1. The ANSWER (generated by another LLM)
2. The SOURCE PASSAGES that were available during generation, labeled with [Source: ...] tags

Your task:
1. Extract every factual claim from the answer (numbers, amounts, findings, dates, entity names, policy details).
2. For each claim, check the cited source (or all sources if none cited).
3. Decide if the claim is GROUNDED (explicitly supported by that source) or NOT GROUNDED (hallucinated, extrapolated, or contradicted).
4. Skip non-factual content (transitions, framing, headers).

Return ONLY valid JSON with this schema:
{
  "claims": [
    {
      "claim_text": "short quote or paraphrase of the claim",
      "cited_source": "Executive Summary, p.11" or null,
      "grounded": true/false,
      "confidence": 0.0 to 1.0,
      "reason": "brief justification"
    }
  ]
}

Rules:
- "grounded": true only if the source EXPLICITLY states the fact. Reasonable paraphrasing is fine.
- "grounded": false if the source is silent on this specific fact, contradicts it, or if the claim extrapolates beyond what's stated.
- "cited_source" should be the EXACT text inside [Source: ...] brackets from the answer. If the claim has no citation, set to null.
- Be strict on numeric claims. "₹124.18 crore" grounded only if source mentions this exact figure.
- Skip filler text, framing sentences, and markdown headers."""


class GroundednessService:
    """Verifies answers against retrieved context."""

    def __init__(
        self,
        config: GroundednessConfig,
        openai_client: OpenAI,
        anthropic_client=None,
        gemini_client=None,
    ):
        self.config = config
        self.openai = openai_client
        self.anthropic = anthropic_client
        self.gemini = gemini_client

    def verify(
        self,
        answer: str,
        retrieval_result: RetrievalResult,
    ) -> GroundednessReport:
        """Verify answer against retrieved context."""
        if not self.config.enabled:
            return GroundednessReport(
                verified=True,
                overall_score=1.0,
                num_claims=0,
                num_grounded=0,
                num_ungrounded=0,
            )

        try:
            # Build the verification prompt
            context_str = retrieval_result.to_context_string(
                include_neighbors=False,  # Verification doesn't need neighbors
                include_semantic_tags=False,
            )

            user_prompt = f"""ANSWER:
{answer}

---

SOURCE PASSAGES:
{context_str}

---

Extract and verify each factual claim. Return JSON."""

            # Dispatch to provider (default: openai)
            if self.config.provider == LLMProvider.CLAUDE and self.anthropic:
                raw = self._verify_claude(user_prompt)
                provider_used = "claude"
            elif self.config.provider == LLMProvider.GEMINI and self.gemini:
                raw = self._verify_gemini(user_prompt)
                provider_used = "gemini"
            else:
                raw = self._verify_openai(user_prompt)
                provider_used = "openai"

            parsed = json.loads(raw)
            claims_raw = parsed.get("claims", [])

            claims = [
                ClaimVerification(
                    claim_text=c.get("claim_text", ""),
                    cited_source=c.get("cited_source"),
                    grounded=bool(c.get("grounded", False)),
                    confidence=float(c.get("confidence", 0.0)),
                    reason=c.get("reason", ""),
                )
                for c in claims_raw
            ]

            num_grounded = sum(1 for c in claims if c.grounded)
            num_claims = len(claims)
            score = num_grounded / num_claims if num_claims > 0 else 1.0

            return GroundednessReport(
                verified=score >= self.config.min_groundedness_score,
                overall_score=score,
                num_claims=num_claims,
                num_grounded=num_grounded,
                num_ungrounded=num_claims - num_grounded,
                claims=claims,
                provider_used=provider_used,
            )

        except Exception as e:
            logger.warning(f"Groundedness verification failed: {e}", exc_info=True)
            # Fail open: if verification fails, don't block the answer
            return GroundednessReport(
                verified=True,  # Assume ok (fail open)
                overall_score=1.0,
                num_claims=0,
                num_grounded=0,
                num_ungrounded=0,
                error=str(e),
            )

    def _verify_openai(self, user_prompt: str) -> str:
        response = self.openai.chat.completions.create(
            model=self.config.openai_model,
            max_tokens=self.config.max_tokens,
            temperature=0.0,
            messages=[
                {"role": "system", "content": GROUNDEDNESS_SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
            response_format={"type": "json_object"},
        )
        return response.choices[0].message.content.strip()

    def _verify_claude(self, user_prompt: str) -> str:
        response = self.anthropic.messages.create(
            model=self.config.claude_model,
            max_tokens=self.config.max_tokens,
            temperature=0.0,
            system=GROUNDEDNESS_SYSTEM_PROMPT
            + "\n\nReturn ONLY valid JSON, no markdown.",
            messages=[{"role": "user", "content": user_prompt}],
        )
        # Claude may wrap JSON in markdown; strip if so
        text = response.content[0].text.strip()
        if text.startswith("```"):
            text = text.split("```")[1]
            if text.startswith("json"):
                text = text[4:]
            text = text.strip()
        return text

    def _verify_gemini(self, user_prompt: str) -> str:
        from google.genai import types

        combined = (
            GROUNDEDNESS_SYSTEM_PROMPT
            + "\n\n---\n\n"
            + user_prompt
            + "\n\nRespond with ONLY valid JSON."
        )
        response = self.gemini.models.generate_content(
            model=self.config.gemini_model,
            contents=[types.Part.from_text(text=combined)],
            config=types.GenerateContentConfig(
                temperature=0.0,
                max_output_tokens=self.config.max_tokens,
                response_mime_type="application/json",
            ),
        )
        return response.text.strip()
